import java.util.Random;

class FortuneQuotes {
    private String[] quotes = {
            "Believe you can and you're halfway there. - Theodore Roosevelt",
            "The only way to do great work is to love what you do. - Steve Jobs",
            "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
            "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
            "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
            "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
            "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
            "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
            "It does not matter how slowly you go as long as you do not stop. - Confucius",
            "In the middle of every difficulty lies opportunity. - Albert Einstein",
            "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
            "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
            "It always seems impossible until it is done. - Nelson Mandela",
            "Your limitation—it's only your imagination.",
            "Push yourself, because no one else is going to do it for you.",
            "Great things never come from comfort zones.",
            "Dream it. Wish it. Do it.",
            "Success doesn’t just find you. You have to go out and get it.",
            "The harder you work for something, the greater you’ll feel when you achieve it.",
            "Dream bigger. Do bigger.",
            "Don’t stop when you’re tired. Stop when you’re done.",
            "Wake up with determination. Go to bed with satisfaction.",
            "Do something today that your future self will thank you for.",
            "Little things make big days.",
            "It’s going to be hard, but hard does not mean impossible.",
            "Don’t wait for opportunity. Create it.",
            "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
            "The key to success is to focus on goals, not obstacles.",
            "Dream it. Believe it. Build it.",
            "Success doesn’t just find you. You have to go out and get it.",
            "The harder you work for something, the greater you’ll feel when you achieve it.",
            "Dream bigger. Do bigger.",
            "Don’t stop when you’re tired. Stop when you’re done.",
            "Wake up with determination. Go to bed with satisfaction.",
            "Do something today that your future self will thank you for.",
            "Little things make big days.",
            "It’s going to be hard, but hard does not mean impossible.",
            "Don’t wait for opportunity. Create it.",
            "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
            "The key to success is to focus on goals, not obstacles.",
            "Dream it. Believe it. Build it.",
            "Dream bigger. Do bigger.",
            "Don’t stop when you’re tired. Stop when you’re done.",
            "Wake up with determination. Go to bed with satisfaction.",
            "Do something today that your future self will thank you for.",
            "Little things make big days.",
            "It’s going to be hard, but hard does not mean impossible.",
            "Don’t wait for opportunity. Create it.",
            "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
            "The key to success is to focus on goals, not obstacles.",
            "Dream it. Believe it. Build it.",
            "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
            "The only way to do great work is to love what you do. - Steve Jobs",
            "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
            "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
            "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
            "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
            "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
            "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
            "It does not matter how slowly you go as long as you do not stop. - Confucius",
            "In the middle of every difficulty lies opportunity. - Albert Einstein",
            "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
            "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
            "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
            "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
            "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
            "It does not matter how slowly you go as long as you do not stop. - Confucius",
            "In the middle of every difficulty lies opportunity. - Albert Einstein",
            "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
            "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
            "It always seems impossible until it is done. - Nelson Mandela",
            "Your limitation—it’s only your imagination.",
            "Push yourself, because no one else is going to do it for you.",
            "Great things never come from comfort zones.",
            "Dream it. Wish it. Do it.",
            "Success doesn’t just find you. You have to go out and get it.",
            "The harder you work for something, the greater you’ll feel when you achieve it.",
            "Dream bigger. Do bigger.",
            "Don’t stop when you’re tired. Stop when you’re done.",
            "Wake up with determination. Go to bed with satisfaction.",
            "Do something today that your future self will thank you for.",
            "Little things make big days.",
            "It’s going to be hard, but hard does not mean impossible.",
            "Don’t wait for opportunity. Create it.",
            "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
            "The key to success is to focus on goals, not obstacles.",
            "Dream it. Believe it. Build it."
    };

    // Method to get a random quote
    public String getRandomQuote() {
        int index = new Random().nextInt(quotes.length);
        return quotes[index];
    }
}
